//
//  File.swift
//  
//
//  Created by Erik Heath Thomas on 8/22/24.
//

import SwiftUI
import AVKit
import Combine


extension AMDVideoPlayer {
    
    /// Defines additional video player events, typically generated by delegate
    /// calls. These are used as the basis of custom notifications posted by the
    /// AMDVideoPlayerCoordinator.
    enum VideoPlayerEvent: String {
        
        /// Indicates an interstitial will be displayed to the user.
        case InterstitialBegan
        
        /// Indicates an interstitial was displayed to the user.
        case InterstitialEnded
        
        /// Indicates a quartile boundary for the current player item was
        /// traversed.
        case QuartileBegan
        
        /// Indicates the user has requested the player to skip to the next
        /// available channel provided by the playback service.
        case SkipToNextChannel
        
        /// Indicates the user has requested the player to skip to the previous
        /// available channel provided by the playback service.
        case SkipToPreviousChannel
        

        var notificationName: Notification.Name {
            switch self {
                case .InterstitialBegan:
                    return AMDVideoPlayer.InterstitialBegan
                    
                case .InterstitialEnded:
                    return AMDVideoPlayer.InterstitialEnded
                    
                case .QuartileBegan:
                    return AMDVideoPlayer.QuartileBegan
                    
                case .SkipToNextChannel:
                    return AMDVideoPlayer.SkipToNextChannel
                    
                case .SkipToPreviousChannel:
                    return AMDVideoPlayer.SkipToPreviousChannel
            }
        }
    }

}
